repos:
  - repo: local
    hooks:
      - id: format-code
        name: Run black
        language: system
        types: [python]
        entry: black
      - id: lint-python-code
        args: ['--max-line-length=99', '--extend-ignore=E203,W503,W605', '--exclude=.venv']
        name: Run flake8
        description: 'Apply a linter to python code'
        entry: flake8
        language: system
        types: [python]
      - id: isort
        args: ['--profile=black']
        name: Run isort
        entry: isort
        language: system
        types: [python]
      - id: pydocstyle
        args: ['--convention=google']
        name: Run pydocstyle
        entry: pydocstyle
        language: system
        types: [python]

